paths:
  uploads: uploads
  static: ''
  collections: ''
  data: ''
  layouts:
collections_config:
  posts:
    path: src/content/post
    output: true
    url: /blog/[slug]/
    description: ''
    icon: notes
    _editables: {}
    _enabled_editors:
      - content
      - data
      - visual
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
  projects:
    path: src/content/project
    output: true
    url: /project/[slug]/
    filter:
    description: ''
    icon: computer
    preview:
      text:
      subtext:
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    _editables: {}
    _enabled_editors:
      - visual
      - data
      - content
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
