paths:
  uploads: uploads
  static: ''
  collections: ''
  data: ''
  layouts:
collections_config:
  posts:
    path: src/content/post
    output: true
    url: /blog/[slug]/
    description: ''
    icon: notes
    _editables: {}
    _enabled_editors:
      - content
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
  projects:
    path: src/content/project
    output: true
    url: /project/[slug]/
    description: ''
    icon: notes
    _editables: {}
    _enabled_editors:
      - visual
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
_enabled_editors:
  - content
  - data
  - visual
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
